blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/finvfamily/finvista/discussions
    about: Ask questions and discuss ideas
  - name: Documentation
    url: https://finvfamily.github.io/finvista/
    about: Check out the documentation
